# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\YandexDisk\MPQ\Qt\FROG\FROG_GUI2.1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(984, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.browser_FROG = QtWidgets.QPushButton(self.centralwidget)
        self.browser_FROG.setObjectName("browser_FROG")
        self.gridLayout_3.addWidget(self.browser_FROG, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.file_SHG = QtWidgets.QLineEdit(self.centralwidget)
        self.file_SHG.setObjectName("file_SHG")
        self.gridLayout_3.addWidget(self.file_SHG, 0, 1, 1, 1)
        self.file_fun = QtWidgets.QLineEdit(self.centralwidget)
        self.file_fun.setObjectName("file_fun")
        self.gridLayout_3.addWidget(self.file_fun, 1, 1, 1, 1)
        self.fix_fund_spec = QtWidgets.QCheckBox(self.centralwidget)
        self.fix_fund_spec.setObjectName("fix_fund_spec")
        self.gridLayout_3.addWidget(self.fix_fund_spec, 1, 4, 1, 1)
        self.checktranspose = QtWidgets.QCheckBox(self.centralwidget)
        self.checktranspose.setObjectName("checktranspose")
        self.gridLayout_3.addWidget(self.checktranspose, 0, 3, 1, 1)
        self.browser_fun = QtWidgets.QPushButton(self.centralwidget)
        self.browser_fun.setObjectName("browser_fun")
        self.gridLayout_3.addWidget(self.browser_fun, 1, 2, 1, 1)
        self.use_fund_spec = QtWidgets.QCheckBox(self.centralwidget)
        self.use_fund_spec.setObjectName("use_fund_spec")
        self.gridLayout_3.addWidget(self.use_fund_spec, 1, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkmaxwavelength = QtWidgets.QCheckBox(self.centralwidget)
        self.checkmaxwavelength.setObjectName("checkmaxwavelength")
        self.gridLayout_7.addWidget(self.checkmaxwavelength, 0, 0, 1, 1)
        self.maxwavelength = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.maxwavelength.setEnabled(False)
        self.maxwavelength.setDecimals(1)
        self.maxwavelength.setMaximum(10000.0)
        self.maxwavelength.setSingleStep(1.0)
        self.maxwavelength.setProperty("value", 2000.0)
        self.maxwavelength.setObjectName("maxwavelength")
        self.gridLayout_7.addWidget(self.maxwavelength, 0, 1, 1, 1)
        self.checkminwavelength = QtWidgets.QCheckBox(self.centralwidget)
        self.checkminwavelength.setObjectName("checkminwavelength")
        self.gridLayout_7.addWidget(self.checkminwavelength, 1, 0, 1, 1)
        self.minwavelength = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.minwavelength.setEnabled(False)
        self.minwavelength.setDecimals(1)
        self.minwavelength.setMaximum(10000.0)
        self.minwavelength.setSingleStep(1.0)
        self.minwavelength.setProperty("value", 1050.0)
        self.minwavelength.setObjectName("minwavelength")
        self.gridLayout_7.addWidget(self.minwavelength, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.FROG_exp = QtWidgets.QGraphicsView(self.layoutWidget)
        self.FROG_exp.setMinimumSize(QtCore.QSize(350, 0))
        self.FROG_exp.setObjectName("FROG_exp")
        self.gridLayout_8.addWidget(self.FROG_exp, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.SpectrumView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.SpectrumView.setObjectName("SpectrumView")
        self.gridLayout_8.addWidget(self.SpectrumView, 6, 1, 1, 1)
        self.check_logscale = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_logscale.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_logscale.setObjectName("check_logscale")
        self.gridLayout_8.addWidget(self.check_logscale, 4, 0, 1, 1)
        self.FROG_sim = QtWidgets.QGraphicsView(self.layoutWidget)
        self.FROG_sim.setObjectName("FROG_sim")
        self.gridLayout_8.addWidget(self.FROG_sim, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 5, 1, 1, 1)
        self.TimeView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.TimeView.setMinimumSize(QtCore.QSize(350, 0))
        self.TimeView.setObjectName("TimeView")
        self.gridLayout_8.addWidget(self.TimeView, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.Type = QtWidgets.QComboBox(self.widget)
        self.Type.setEditable(True)
        self.Type.setCurrentText("")
        self.Type.setMaxVisibleItems(5)
        self.Type.setMaxCount(10)
        self.Type.setObjectName("Type")
        self.horizontalLayout_8.addWidget(self.Type)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.check_random = QtWidgets.QRadioButton(self.widget)
        self.check_random.setEnabled(True)
        self.check_random.setChecked(True)
        self.check_random.setObjectName("check_random")
        self.horizontalLayout_6.addWidget(self.check_random)
        self.check_flatPH = QtWidgets.QRadioButton(self.widget)
        self.check_flatPH.setObjectName("check_flatPH")
        self.horizontalLayout_6.addWidget(self.check_flatPH)
        self.check_GDD = QtWidgets.QRadioButton(self.widget)
        self.check_GDD.setObjectName("check_GDD")
        self.horizontalLayout_6.addWidget(self.check_GDD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_14 = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_14.setPalette(palette)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.error_message = QtWidgets.QTextEdit(self.widget)
        self.error_message.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.error_message.setPalette(palette)
        self.error_message.setReadOnly(True)
        self.error_message.setObjectName("error_message")
        self.verticalLayout_2.addWidget(self.error_message)
        self.check_symmetry = QtWidgets.QCheckBox(self.widget)
        self.check_symmetry.setObjectName("check_symmetry")
        self.verticalLayout_2.addWidget(self.check_symmetry)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkdelaycorrection = QtWidgets.QCheckBox(self.widget)
        self.checkdelaycorrection.setObjectName("checkdelaycorrection")
        self.horizontalLayout_3.addWidget(self.checkdelaycorrection)
        self.delay_correction = QtWidgets.QDoubleSpinBox(self.widget)
        self.delay_correction.setEnabled(False)
        self.delay_correction.setDecimals(2)
        self.delay_correction.setMaximum(10.0)
        self.delay_correction.setSingleStep(0.1)
        self.delay_correction.setProperty("value", 2.0)
        self.delay_correction.setObjectName("delay_correction")
        self.horizontalLayout_3.addWidget(self.delay_correction)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_bkgsubtract = QtWidgets.QCheckBox(self.widget)
        self.check_bkgsubtract.setObjectName("check_bkgsubtract")
        self.horizontalLayout_4.addWidget(self.check_bkgsubtract)
        self.bkg = QtWidgets.QDoubleSpinBox(self.widget)
        self.bkg.setEnabled(False)
        self.bkg.setDecimals(4)
        self.bkg.setMaximum(1.0)
        self.bkg.setSingleStep(0.001)
        self.bkg.setProperty("value", 0.008)
        self.bkg.setObjectName("bkg")
        self.horizontalLayout_4.addWidget(self.bkg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.check_bkgedge = QtWidgets.QCheckBox(self.widget)
        self.check_bkgedge.setObjectName("check_bkgedge")
        self.verticalLayout_2.addWidget(self.check_bkgedge)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.iternumber = QtWidgets.QSpinBox(self.widget)
        self.iternumber.setMinimum(1)
        self.iternumber.setMaximum(10000000)
        self.iternumber.setProperty("value", 1000)
        self.iternumber.setObjectName("iternumber")
        self.gridLayout_2.addWidget(self.iternumber, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.goal = QtWidgets.QDoubleSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goal.sizePolicy().hasHeightForWidth())
        self.goal.setSizePolicy(sizePolicy)
        self.goal.setDecimals(5)
        self.goal.setSingleStep(1e-05)
        self.goal.setProperty("value", 0.0001)
        self.goal.setObjectName("goal")
        self.gridLayout_2.addWidget(self.goal, 1, 2, 1, 1)
        self.size = QtWidgets.QSpinBox(self.widget)
        self.size.setMinimum(1)
        self.size.setMaximum(100)
        self.size.setProperty("value", 10)
        self.size.setDisplayIntegerBase(10)
        self.size.setObjectName("size")
        self.gridLayout_2.addWidget(self.size, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Swidth = QtWidgets.QLCDNumber(self.widget)
        self.Swidth.setToolTip("")
        self.Swidth.setSmallDecimalPoint(False)
        self.Swidth.setDigitCount(6)
        self.Swidth.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Swidth.setProperty("value", 0.0)
        self.Swidth.setObjectName("Swidth")
        self.gridLayout_6.addWidget(self.Swidth, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.duration = QtWidgets.QLCDNumber(self.widget)
        self.duration.setFrameShadow(QtWidgets.QFrame.Plain)
        self.duration.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.duration.setProperty("value", 1.0)
        self.duration.setObjectName("duration")
        self.gridLayout_6.addWidget(self.duration, 1, 0, 1, 1)
        self.duration_tl = QtWidgets.QLCDNumber(self.widget)
        self.duration_tl.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.duration_tl.setProperty("value", 1.0)
        self.duration_tl.setObjectName("duration_tl")
        self.gridLayout_6.addWidget(self.duration_tl, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 1, 1, 1)
        self.Sstep = QtWidgets.QLCDNumber(self.widget)
        self.Sstep.setToolTip("")
        self.Sstep.setSmallDecimalPoint(False)
        self.Sstep.setDigitCount(6)
        self.Sstep.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Sstep.setProperty("value", 0.0)
        self.Sstep.setObjectName("Sstep")
        self.gridLayout_6.addWidget(self.Sstep, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 2, 1, 1, 1)
        self.Tstep = QtWidgets.QLCDNumber(self.widget)
        self.Tstep.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Tstep.setProperty("value", 1.0)
        self.Tstep.setObjectName("Tstep")
        self.gridLayout_6.addWidget(self.Tstep, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.duration_e = QtWidgets.QLCDNumber(self.widget)
        self.duration_e.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.duration_e.setProperty("intValue", 1)
        self.duration_e.setObjectName("duration_e")
        self.gridLayout_6.addWidget(self.duration_e, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.step = QtWidgets.QLCDNumber(self.widget)
        self.step.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.step.setProperty("value", 1.0)
        self.step.setObjectName("step")
        self.gridLayout.addWidget(self.step, 1, 0, 1, 1)
        self.error = QtWidgets.QLCDNumber(self.widget)
        self.error.setToolTip("")
        self.error.setSmallDecimalPoint(False)
        self.error.setDigitCount(7)
        self.error.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.error.setProperty("value", 0.0)
        self.error.setObjectName("error")
        self.gridLayout.addWidget(self.error, 1, 1, 1, 1)
        self.timer = QtWidgets.QLCDNumber(self.widget)
        self.timer.setSmallDecimalPoint(False)
        self.timer.setDigitCount(4)
        self.timer.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.timer.setProperty("value", 0.0)
        self.timer.setObjectName("timer")
        self.gridLayout.addWidget(self.timer, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setEnabled(True)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 9777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setIndent(0)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.multi_grid = QtWidgets.QCheckBox(self.widget)
        self.multi_grid.setObjectName("multi_grid")
        self.horizontalLayout_5.addWidget(self.multi_grid)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBt = QtWidgets.QPushButton(self.widget)
        self.startBt.setObjectName("startBt")
        self.horizontalLayout.addWidget(self.startBt)
        self.stopBt = QtWidgets.QPushButton(self.widget)
        self.stopBt.setObjectName("stopBt")
        self.horizontalLayout.addWidget(self.stopBt)
        self.continueBt = QtWidgets.QPushButton(self.widget)
        self.continueBt.setObjectName("continueBt")
        self.horizontalLayout.addWidget(self.continueBt)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 18))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave_FROG = QtWidgets.QAction(MainWindow)
        self.actionsave_FROG.setObjectName("actionsave_FROG")
        self.actionsave_time = QtWidgets.QAction(MainWindow)
        self.actionsave_time.setObjectName("actionsave_time")
        self.actionsave_spectrum = QtWidgets.QAction(MainWindow)
        self.actionsave_spectrum.setObjectName("actionsave_spectrum")
        self.actionsave_best_D_scan = QtWidgets.QAction(MainWindow)
        self.actionsave_best_D_scan.setObjectName("actionsave_best_D_scan")
        self.actionsave_mean_D_scan = QtWidgets.QAction(MainWindow)
        self.actionsave_mean_D_scan.setObjectName("actionsave_mean_D_scan")
        self.actionsave_all = QtWidgets.QAction(MainWindow)
        self.actionsave_all.setObjectName("actionsave_all")
        self.actionsave_experimental_FROG = QtWidgets.QAction(MainWindow)
        self.actionsave_experimental_FROG.setObjectName("actionsave_experimental_FROG")
        self.menufile.addAction(self.actionsave_FROG)
        self.menufile.addAction(self.actionsave_experimental_FROG)
        self.menufile.addAction(self.actionsave_time)
        self.menufile.addAction(self.actionsave_spectrum)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionsave_all)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.Type.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Slava FROG v2.0"))
        self.label_2.setText(_translate("MainWindow", "fundamental spectrum (optional)"))
        self.browser_FROG.setText(_translate("MainWindow", "browser"))
        self.label.setText(_translate("MainWindow", "FROG trace"))
        self.fix_fund_spec.setText(_translate("MainWindow", "fix fundamental spectrum"))
        self.checktranspose.setText(_translate("MainWindow", "transpose"))
        self.browser_fun.setText(_translate("MainWindow", "browser"))
        self.use_fund_spec.setText(_translate("MainWindow", "use to start with"))
        self.checkmaxwavelength.setText(_translate("MainWindow", "max wavelength nm"))
        self.checkminwavelength.setText(_translate("MainWindow", "min wavelength nm"))
        self.label_17.setText(_translate("MainWindow", "Reconstracted FROG"))
        self.label_11.setText(_translate("MainWindow", "Experimental FROG"))
        self.check_logscale.setText(_translate("MainWindow", "log scale"))
        self.FROG_sim.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>FROG</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Time"))
        self.label_16.setText(_translate("MainWindow", "Spectrum"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">FROG type</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Start with Phase:"))
        self.check_random.setText(_translate("MainWindow", "random"))
        self.check_flatPH.setText(_translate("MainWindow", "flat"))
        self.check_GDD.setText(_translate("MainWindow", "GDD"))
        self.label_14.setText(_translate("MainWindow", "errors"))
        self.check_symmetry.setText(_translate("MainWindow", "symmetrization (applied after pressing start)"))
        self.checkdelaycorrection.setText(_translate("MainWindow", "delay correction"))
        self.check_bkgsubtract.setText(_translate("MainWindow", "subtract background"))
        self.check_bkgedge.setText(_translate("MainWindow", "substract background defined at the delay borders"))
        self.label_8.setText(_translate("MainWindow", "goal G error"))
        self.label_7.setText(_translate("MainWindow", "max Number of steps"))
        self.label_9.setText(_translate("MainWindow", "max array size 2**"))
        self.Swidth.setWhatsThis(_translate("MainWindow", "error"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>&tau; FWHM fs </p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "W FWHM nm"))
        self.label_20.setText(_translate("MainWindow", "W step nm"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>&tau; trans.lim. fs </p></body></html>"))
        self.Sstep.setWhatsThis(_translate("MainWindow", "error"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>&tau; step fs</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>τ e^-2 fs</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "reconstr. step"))
        self.label_5.setText(_translate("MainWindow", "recons. error (G)"))
        self.label_15.setText(_translate("MainWindow", "passed time sec"))
        self.error.setWhatsThis(_translate("MainWindow", "error"))
        self.label_21.setText(_translate("MainWindow", "progress (steps)"))
        self.multi_grid.setText(_translate("MainWindow", "use multi-grid algorithm"))
        self.startBt.setText(_translate("MainWindow", "start"))
        self.stopBt.setText(_translate("MainWindow", "stop"))
        self.continueBt.setText(_translate("MainWindow", "continue"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionsave_FROG.setText(_translate("MainWindow", "save reconstructed FROG"))
        self.actionsave_time.setText(_translate("MainWindow", "save time"))
        self.actionsave_spectrum.setText(_translate("MainWindow", "save spectrum"))
        self.actionsave_best_D_scan.setText(_translate("MainWindow", "save best D-scan"))
        self.actionsave_mean_D_scan.setText(_translate("MainWindow", "save mean D-scan"))
        self.actionsave_all.setText(_translate("MainWindow", "save all"))
        self.actionsave_experimental_FROG.setText(_translate("MainWindow", "save experimental FROG"))
